# Site settings
title: Omar Lugo
email: lugo.oe@gmail.com  
description: "data scientist"
baseurl: ""
url: "http://lugomar.github.io"
twitter_username: lugo_oe
github_username:  lugomar

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
